### PR TITLE
Ember version rev

### PR DESCRIPTION
**Pull request by ike**
Ran `ember init`, cleaned up a bit. This branch is running with errors.

### CODE REVIEW

**Comment by ike** [comment]
Errors:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/potus/Code/wildland/ember-bootstrap-controls/tmp/source_map_concat-input_base_path-2HdEpwhm.tmp/undefined/bootstrap-datepicker/dist/js/bootstrap-datepicker.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise (/Users/potus/Code/wildland/ember-bootstrap-controls/node_modules/rsvp/dist/rsvp.js:1077:31)
```

**Comment by ike** [comment]
We want to start the new Labbee project on Ember 2.x. We have to rev quite a few libraries before Trailhead will run successfully on Ember 2.x.

**Comment by chadzink** [comment]
Why are we using Ember 2.x on that project? The time that will add is very expensive.

**Comment by chadzink** [comment]
Just need to define the cost to do this and where it is coming from.

**Comment by Samsinite** [comment]
Closing in favor of #83

**Pull request closed without merging**
