### PR TITLE
Bootstrap-4 Integration

### PR DESCRIPTION
**Pull request by temecom**
- Upgraded to Bootstrap-4 Beta
- Changed console.logs to Ember.Logger.debug
- Updated Pagination to new Bootstrap-4 format
- Corrected dropped '0' in telephone mask - use x for placeholder digit.

### CODE REVIEW

**Comment by Samsinite** [comment]
Wow this looks great, thanks!

**Comment by Samsinite** [comment]
Unless you get to this sooner, since I can't modify this branch to resolve the conflicts, I'm going to copy it into another branch and resolve so it can be merged.

**Comment by temecom** [comment]
Sorry I have been buried. I will look at this tonight if you haven't merged already. 
Chris

**Comment by Samsinite** [comment]
Completely understand. I have not looked at it yet, goahead. If I have more time to take a look at it, I'll let you know. Much appreciated, thanks.

**Comment by temecom** [comment]
I am not sure how to fix conflicts across forks... I don't see the conflict when I pull from the upstream (this one). I created a new branch: bootstrap-4 that you should have edit rights in the pull request. I hope that helps.

**Comment by temecom** [comment]
OK I think I have it - see new pull request

**Pull request closed without merging**
