### PR TITLE
Ready for publish. Fixes #189

### LINKED ISSUE #189: Finalize CHANGELOG.md and version.
- [ ] Move features into correct version
- [ ] Update package.json
- [ ] Publish to npm

### PR DESCRIPTION
**Pull request by jweakley**
Pull Request Description:
(Description in grammatically correct, complete sentences)

New Pull Request Checklist:
- [x] Reviewed [contributing guidelines](CONTRIBUTING.md).
- [x] [good commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
- [x] Github issue added, if it exists.
- [x] Added an entry to the [Changelog](CHANGELOG.md).
- [x] All tests passing: run `npm test`.
- [x] New component tests include [ember-a11y-testing](https://github.com/ember-a11y/ember-a11y-testing) to test accessibility.

### CODE REVIEW

**Comment by jweakley** [comment]
@Samsinite I believe that is partially why we are doing a beta release and not a normal release. We will talk about how to address this in the next sprint planning. I know we also had been talking about contextual forms which may effect this.

**Comment by flarinerin** [comment]
@jweakley maybe just go ahead and do it... It's really annoying @Samsinite and I don't think it'd take too long and it would be good practice.

**Comment by jweakley** [comment]
I opened an issue for Sam's feedback: https://github.com/wildland/ember-bootstrap-controls/issues/215

**Comment by Samsinite** [comment]
Thanks, yeah it has been bothering me. If we don't follow conventions, than they don't mean anything :)

**Pull request closed without merging**
